### ISSUE TITLE
Some code blocks cannot be fully displayed

### ISSUE THREAD

**Issue by tzSharing** [vlang/docs#12]
Some code blocks cannot be fully displayed.
For example: `v-types.html`, even if you slide the slider to the far right, there are still some text that cannot be displayed.
![1](https://github.com/user-attachments/assets/e240a845-06c0-4b1c-b1fc-7fdf76dea853)
![2](https://github.com/user-attachments/assets/7411c43b-ed1b-4a37-859e-ed00ccadabce)
![3](https://github.com/user-attachments/assets/3968f5d3-542c-43f4-b8b9-bc4e44cf759d)
![4](https://github.com/user-attachments/assets/2e9256c5-0412-49f0-b9be-8f50fb040e2a)

**Comment by ttytm** [comment]
I should have been resolved in the linked PR, so I think it can be closed @spytheman

**Comment by spytheman** [comment]
Yes, it is now working. Thanks @ttytm .
