### ISSUE TITLE
some lists are not well parsed

### ISSUE THREAD

**Issue by MedLabs** [vlang/docs#5]
![image](https://github.com/vlang/docs/assets/6123009/05d6bbfc-15cb-415e-ac18-0a239addb2ae)

check the a) and b) and c) 
they should be :
a) ...
b) ... 
c) ...

**Comment by spytheman** [comment]
Fixed in https://github.com/vlang/v/commit/3326392ce2630075b9c1a66d8fe8e795ab457ebe .

**Comment by spytheman** [comment]
![image](https://github.com/user-attachments/assets/e253fdc0-7286-41e5-aea8-0600585dab0c)

I decided to use 1. .. 4. instead of a) .. d), because the next line talks about the 3rd column, and it will be less confusing that way imho.
